Cleaning and simplifying project (#4)
* apply patch from cci-demo-docker

* scrape docker off

* run and validate service

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,26 +2,70 @@ version: 2
 jobs:
   build:
     docker:
-      - image: golang:1.6.2
+      # using custom image, see .circleci/images/primary/Dockerfile
+      - image: circleci/cci-demo-go-primary:0.0.2
       - image: postgres:9.4.1
         environment:
           POSTGRES_USER: ubuntu
-          POSTGRES_DB: service_test
+          POSTGRES_DB: contacts
+
     working_directory: /go/src/github.com/circleci/cci-demo-go
+
+    environment:
+      TEST_RESULTS: /tmp/test-results
+
     steps:
       - checkout
+
       - run:
-          name: "Install JUnit & Setup Test Path"
+          name: Waiting for Postgres to be ready
           command: |
-            go get github.com/jstemmer/go-junit-report
-            mkdir -p /tmp/test-results
+            for i in `seq 1 10`;
+            do
+              nc -z localhost 5432 && echo Success && exit 0
+              echo -n .
+              sleep 1
+            done
+            echo Failed waiting for Postgress && exit 1
+
+      - run: mkdir -p $TEST_RESULTS
+
+      # This should be in cursom primary image, here is just for the sake of explanation
       - run:
+          name: Install JUnit
+          command: go get github.com/jstemmer/go-junit-report
+
+      - run:
+          name: Run unit tests
           environment:
-            DATABASE_URL: "postgres://ubuntu@localhost:5432/service_test?sslmode=disable"
+            CONTACTS_DB_URL: "postgres://ubuntu@localhost:5432/contacts?sslmode=disable"
+            CONTACTS_DB_MIGRATIONS: /go/src/github.com/circleci/cci-demo-go/db/migrations
           command: |
-            set -eu
-            mkdir -p /tmp/test-results
-            go get -t -d -v ./...
-            go test -v -race ./... | go-junit-report > /tmp/test-results/unit-tests.xml
+            set -ou pipefail
+            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
+            # Notice this `set -o pipefail`, this will cause script to fail if `make test` fails
+            # without this option script will return success regardless of testing result due to pipe after test command
+            make test | tee ${TEST_RESULTS}/go-test.out
+
+      - run:
+          name: Build service
+          command: make
+
+      - run:
+          name: Start service
+          environment:
+            CONTACTS_DB_URL: "postgres://ubuntu@localhost:5432/contacts?sslmode=disable"
+            CONTACTS_DB_MIGRATIONS: /go/src/github.com/circleci/cci-demo-go/db/migrations
+          command: ./workdir/contacts
+          background: true
+
+      - run:
+          name: Validate service is working
+          command: curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/contacts/test
+
+      - store_artifacts:
+          path: /tmp/test-results
+          destination: raw-test-output
+
       - store_test_results:
           path: /tmp/test-results
